language: erlang
notifications:
  hipchat:
    rooms:
      secure: RbtwL2/xaEqwbWXYpaPyngptdi4X4fwQwLFutraV8bVAYZMU6OhtL1dT1JiLeh5WTlto9jgktXrmoAqSISmCibimH0aXc42j93B4UJ22rJTQB2pMFCCGoVGnkkbvypmsKeB1VDLZKt0GUe5UTiMUB2o96Ish9gZayNI4Cm7YjTY=
otp_release:
   - 17.1
   - 17.0
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
   - R14B04
   - R14B03
   - R14B02
script: make rebuild
